"use client";

import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import { Provider } from "react-redux";
import store from "../../store";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Beat Machine",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"
          onLoad={() => alert("Script loaded successfully!")}></script>
      </head>
      <Provider store={store}>
        <body className={inter.className}>
          {children}

          <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></script>
        </body>
      </Provider>
    </html>
  );
}
