import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import { Provider } from "react-redux";
import store from "../../store";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Beat Machine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={inter.className}>{children}</body>
      </Provider>
    </html>
  );
}
